---

- name: update apt mirror URLs
  command: sed -i 's/us.archive.ubuntu.com/mirrors.us.kernel.org/g' /etc/apt/sources.list
- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - automake
    - autoconf
    - erlang
